#ifndef CONSTS_H
#define CONSTS_H

#define MAIN_MENU_PAGE 0
#define BASIC_DISTRIBUTION_INPUT_PAGE 1
#define MIX_DISTRIBUTION_INPUT_PAGE 2
#define SELECT_OPERATION_FOR_DISTIBUTION_BY_COEFS_PAGE 3
#define STATS_BY_COEFS_PAGE 4
#define DENSITY_BY_COEFS_PAGE 5
#define GENERATE_DATASET_PAGE 6
#define SELECT_OPERATION_FOR_DISTIBUTION_BY_DATASET_PAGE 7
#define STATS_BY_DATASET_PAGE 8
#define DENSITY_BY_DATASET_PAGE 9
#define SHOW_DATASET_PAGE 10
#define DATASET_TO_FILE_PAGE 11
#define GENERATE_DATASET_BY_DENSITY_PAGE 12

#define LAYER_2_PAGE_SHIFT 3
#define LAYER_3_PAGE_SHIFT 7

#define UNDEFINED_DATATYPE 0
#define GENERAL_DISTRIBUTION_DATATYPE 1
#define MIX_DISTRIBUTION_DATATYPE 2
#define EMPIRICAL_DATATYPE 3

#endif
