#ifndef CONSTS_H
#define CONSTS_H

#define MAIN_MENU_PAGE 0
#define BASIC_DISTRIBUTION_INPUT_PAGE 1
#define CLASS_OF_BASIC_DISTRIBUTION_INPUT_PAGE 2
#define MIX_DISTRIBUTION_INPUT_PAGE 3
#define CLASS_OF_MIX_DISTRIBUTION_INPUT_PAGE 4
#define TEST 5
#define SELECT_OPERATION_FOR_DISTIBUTION_BY_COEFS_PAGE 6
#define STATS_BY_COEFS_PAGE 7
#define DENSITY_BY_COEFS_PAGE 8
#define GENERATE_DATASET_PAGE 9
#define SELECT_OPERATION_FOR_DISTIBUTION_BY_DATASET_PAGE 10
#define STATS_BY_DATASET_PAGE 11
#define DENSITY_BY_DATASET_PAGE 112
#define SHOW_DATASET_PAGE 13
#define DATASET_TO_FILE_PAGE 14
#define GENERATE_DATASET_BY_DENSITY_PAGE 15


#define LAYER_2_PAGE_SHIFT 6
#define LAYER_3_PAGE_SHIFT 10

#define UNDEFINED_DATATYPE 0
#define GENERAL_DISTRIBUTION_DATATYPE 1
#define CLASS_OF_GENERAL_DISTRIBUTION_DATATYPE 2
#define MIX_DISTRIBUTION_DATATYPE 3
#define CLASS_OF_MIX_DISTRIBUTION_DATATYPE 4
#define EMPIRICAL_DATATYPE 5

#endif
